// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// Package maps implements helper functions for map
package maps

// IntBoolKeys returns a slice of int map keys
func IntBoolKeys(m map[int]bool) []int {
	result := make([]int, len(m))
	i := 0
	for k := range m {
		result[i] = k
		i++
	}
	return result
}

// IntBoolIsEq returns true when two maps have the same keys and values
// (using value semantics).
func IntBoolIsEq(m1, m2 map[int]bool) bool {
	if len(m1) != len(m2) {
		return false
	}
	for k1, v1 := range m1 {
		if v2, ok := m2[k1]; ok == true {
			if v2 != v1 {
				return false
			}
		} else {
			return false
		}
	}
	return true
}

// Package maps implements helper functions for map

// IntIntKeys returns a slice of int map keys
func IntIntKeys(m map[int]int) []int {
	result := make([]int, len(m))
	i := 0
	for k := range m {
		result[i] = k
		i++
	}
	return result
}

// IntIntIsEq returns true when two maps have the same keys and values
// (using value semantics).
func IntIntIsEq(m1, m2 map[int]int) bool {
	if len(m1) != len(m2) {
		return false
	}
	for k1, v1 := range m1 {
		if v2, ok := m2[k1]; ok == true {
			if v2 != v1 {
				return false
			}
		} else {
			return false
		}
	}
	return true
}

// Package maps implements helper functions for map

// IntStringKeys returns a slice of int map keys
func IntStringKeys(m map[int]string) []int {
	result := make([]int, len(m))
	i := 0
	for k := range m {
		result[i] = k
		i++
	}
	return result
}

// IntStringIsEq returns true when two maps have the same keys and values
// (using value semantics).
func IntStringIsEq(m1, m2 map[int]string) bool {
	if len(m1) != len(m2) {
		return false
	}
	for k1, v1 := range m1 {
		if v2, ok := m2[k1]; ok == true {
			if v2 != v1 {
				return false
			}
		} else {
			return false
		}
	}
	return true
}

// Package maps implements helper functions for map

// StringBoolKeys returns a slice of string map keys
func StringBoolKeys(m map[string]bool) []string {
	result := make([]string, len(m))
	i := 0
	for k := range m {
		result[i] = k
		i++
	}
	return result
}

// StringBoolIsEq returns true when two maps have the same keys and values
// (using value semantics).
func StringBoolIsEq(m1, m2 map[string]bool) bool {
	if len(m1) != len(m2) {
		return false
	}
	for k1, v1 := range m1 {
		if v2, ok := m2[k1]; ok == true {
			if v2 != v1 {
				return false
			}
		} else {
			return false
		}
	}
	return true
}

// Package maps implements helper functions for map

// StringIntKeys returns a slice of string map keys
func StringIntKeys(m map[string]int) []string {
	result := make([]string, len(m))
	i := 0
	for k := range m {
		result[i] = k
		i++
	}
	return result
}

// StringIntIsEq returns true when two maps have the same keys and values
// (using value semantics).
func StringIntIsEq(m1, m2 map[string]int) bool {
	if len(m1) != len(m2) {
		return false
	}
	for k1, v1 := range m1 {
		if v2, ok := m2[k1]; ok == true {
			if v2 != v1 {
				return false
			}
		} else {
			return false
		}
	}
	return true
}

// Package maps implements helper functions for map

// StringStringKeys returns a slice of string map keys
func StringStringKeys(m map[string]string) []string {
	result := make([]string, len(m))
	i := 0
	for k := range m {
		result[i] = k
		i++
	}
	return result
}

// StringStringIsEq returns true when two maps have the same keys and values
// (using value semantics).
func StringStringIsEq(m1, m2 map[string]string) bool {
	if len(m1) != len(m2) {
		return false
	}
	for k1, v1 := range m1 {
		if v2, ok := m2[k1]; ok == true {
			if v2 != v1 {
				return false
			}
		} else {
			return false
		}
	}
	return true
}
