// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package sets

import (
	"fmt"
	"strings"
)

// Int8Set is an implementation of a set holding integers.
// It uses a map in the background.
type Int8Set map[int8]bool

func (s Int8Set) String() string {
	var b strings.Builder
	for k := range s {
		fmt.Fprintf(&b, "%d ", k)
	}
	result := fmt.Sprintf("Int8Set{ %s}", b.String())
	return result
}

// Len returns the length (the number of members)
// of a set.
func (s Int8Set) Len() int {
	return len(s)
}

// Add adds an element to the set.
// If the element is already present, nothing happens.
func (s Int8Set) Add(el int8) {
	s[el] = true
}

// Contains tests whether an element is present in a set.
func (s Int8Set) Contains(el int8) bool {
	_, result := s[el]
	return result
}

// IsEq tests for equality of two sets
func (s Int8Set) IsEq(other Int8Set) bool {
	slen := s.Len()
	olen := other.Len()
	if slen != olen {
		return false
	}
	if slen == 0 {
		return true
	}
	for k := range s {
		if !other.Contains(k) {
			return false
		}
	}
	return true
}

// NewInt8Set creates a new empty set
func NewInt8Set() Int8Set {
	result := make(Int8Set)
	return result
}

// Int8SetFromSlice creates a set from a slice
func Int8SetFromSlice(s []int8) Int8Set {
	result := make(Int8Set)
	for _, k := range s {
		result.Add(k)
	}
	return result
}

// Int16Set is an implementation of a set holding integers.
// It uses a map in the background.
type Int16Set map[int16]bool

func (s Int16Set) String() string {
	var b strings.Builder
	for k := range s {
		fmt.Fprintf(&b, "%d ", k)
	}
	result := fmt.Sprintf("Int16Set{ %s}", b.String())
	return result
}

// Len returns the length (the number of members)
// of a set.
func (s Int16Set) Len() int {
	return len(s)
}

// Add adds an element to the set.
// If the element is already present, nothing happens.
func (s Int16Set) Add(el int16) {
	s[el] = true
}

// Contains tests whether an element is present in a set.
func (s Int16Set) Contains(el int16) bool {
	_, result := s[el]
	return result
}

// IsEq tests for equality of two sets
func (s Int16Set) IsEq(other Int16Set) bool {
	slen := s.Len()
	olen := other.Len()
	if slen != olen {
		return false
	}
	if slen == 0 {
		return true
	}
	for k := range s {
		if !other.Contains(k) {
			return false
		}
	}
	return true
}

// NewInt16Set creates a new empty set
func NewInt16Set() Int16Set {
	result := make(Int16Set)
	return result
}

// Int16SetFromSlice creates a set from a slice
func Int16SetFromSlice(s []int16) Int16Set {
	result := make(Int16Set)
	for _, k := range s {
		result.Add(k)
	}
	return result
}

// Int32Set is an implementation of a set holding integers.
// It uses a map in the background.
type Int32Set map[int32]bool

func (s Int32Set) String() string {
	var b strings.Builder
	for k := range s {
		fmt.Fprintf(&b, "%d ", k)
	}
	result := fmt.Sprintf("Int32Set{ %s}", b.String())
	return result
}

// Len returns the length (the number of members)
// of a set.
func (s Int32Set) Len() int {
	return len(s)
}

// Add adds an element to the set.
// If the element is already present, nothing happens.
func (s Int32Set) Add(el int32) {
	s[el] = true
}

// Contains tests whether an element is present in a set.
func (s Int32Set) Contains(el int32) bool {
	_, result := s[el]
	return result
}

// IsEq tests for equality of two sets
func (s Int32Set) IsEq(other Int32Set) bool {
	slen := s.Len()
	olen := other.Len()
	if slen != olen {
		return false
	}
	if slen == 0 {
		return true
	}
	for k := range s {
		if !other.Contains(k) {
			return false
		}
	}
	return true
}

// NewInt32Set creates a new empty set
func NewInt32Set() Int32Set {
	result := make(Int32Set)
	return result
}

// Int32SetFromSlice creates a set from a slice
func Int32SetFromSlice(s []int32) Int32Set {
	result := make(Int32Set)
	for _, k := range s {
		result.Add(k)
	}
	return result
}

// IntSet is an implementation of a set holding integers.
// It uses a map in the background.
type IntSet map[int]bool

func (s IntSet) String() string {
	var b strings.Builder
	for k := range s {
		fmt.Fprintf(&b, "%d ", k)
	}
	result := fmt.Sprintf("IntSet{ %s}", b.String())
	return result
}

// Len returns the length (the number of members)
// of a set.
func (s IntSet) Len() int {
	return len(s)
}

// Add adds an element to the set.
// If the element is already present, nothing happens.
func (s IntSet) Add(el int) {
	s[el] = true
}

// Contains tests whether an element is present in a set.
func (s IntSet) Contains(el int) bool {
	_, result := s[el]
	return result
}

// IsEq tests for equality of two sets
func (s IntSet) IsEq(other IntSet) bool {
	slen := s.Len()
	olen := other.Len()
	if slen != olen {
		return false
	}
	if slen == 0 {
		return true
	}
	for k := range s {
		if !other.Contains(k) {
			return false
		}
	}
	return true
}

// NewIntSet creates a new empty set
func NewIntSet() IntSet {
	result := make(IntSet)
	return result
}

// IntSetFromSlice creates a set from a slice
func IntSetFromSlice(s []int) IntSet {
	result := make(IntSet)
	for _, k := range s {
		result.Add(k)
	}
	return result
}
